### PR TITLE
If the rake task for uploading source maps is found, run it

### PR DESCRIPTION
**Pull request by mattgibson**

### CODE REVIEW

**Comment by tomchipchase** [comment]
where has this project come from? are we maintaining our own build pack?

**Comment by mylescc** [comment]
wat :+1:

**Comment by mattgibson** [comment]
I made this for webpack when we moved to using it. All it does is runs the rake task to compile the webpack assets at the right point in the Heroku deploy process. All the config etc is in the web project. Now, we need to upload source maps to Rollbar when the deploy to production happens and this seems like the only way to do it. Again, the config etc is in the web project and this just triggers it at the right point. Minimal maintenance :)

**Comment by tomchipchase** [comment]
:+1:

**Pull request merged**
